### ISSUE TITLE
Instruction for newbie demo, please.

### ISSUE THREAD

**Issue by songwutk** [hexya-erp/hexya#106]
I'm new for golang. I'd like to install demo in my ubuntu pc. Please note installation for fast review.

**Comment by npiganeau** [comment]
Thanks for your interest in Hexya. You can find documentation here: http://hexya.io/docs/ and especially http://hexya.io/docs/install/

I've just updated the hexya-demo project so that it builds the accounting module.

Please note that:
- Building hexya requires at least 8GB of RAM and may fail on limited hardware. We hope this will improve when Go will have generics.
- Hexya is really WIP. Many pages may fail.

**Comment by songwutk** [comment]
Thanks.
