### ISSUE TITLE
Error on command : hexya i18n update openacademy/ -l fr 

### ISSUE THREAD

**Issue by JulienPozzNDP** [hexya-erp/hexya#13]
This command generates the following error : 

Unable to build program, [error no initial packages were loaded caller updatePOFiles]

**Comment by halybang** [comment]
This error occurs because hexya try to create file in <project_dir>/hexya/server/i18n/<module_name>/
I think hexya should create *po file in origin directory.
For ex, with `base` modules, vi.po/en.po ... should be create in
`$GOPATH/src/github.com/hexya-erp/hexya-base/base/i18n/` instead `<project_dir>/hexya/server/i18n/base/`

**Comment by npiganeau** [comment]
`hexya generate` makes a symlink of `$GOPATH/src/<path to module>` in `<project_dir>/hexya/server/i18n/<module_name>/` so it should not be an issue.

Though I probably need to make the symlinks in `hexya i18n` too so that we don't have to call `hexya generate` before.

**Comment by halybang** [comment]
You forget call MkdirAll :)
So, If I do it manual from bash: `$mkdir -p <project_dir>/hexya/server/i18n/<module_name>/`, it will work.
