### ISSUE TITLE
Binary executable deploy?

### ISSUE THREAD

**Issue by halybang** [hexya-erp/hexya#4]
We can not deploy hexya as binary executable when invoke `hexya server `  (because of calling cleanModuleSymlinks/createModuleSymlinks ).
IMHO, `cleanModuleSymlinks/createModuleSymlinks` should be call when invoke `hexya generate`

**Comment by npiganeau** [comment]
Hexya cannot be deployed as binary anyway:
1. Because it needs all resource files (from all the folders which are symlinked) as you said
2. Because it is configurable at compile time (to choose the modules you want).

So because of 1 and 2, I did not put much importance about deployment for the moment.

But I plan to do a `hexya bundle` or equivalent to get a distributable form of Hexya (maybe a zip or a single binary with go-binddata, I don't know yet)

**Comment by halybang** [comment]
I created a simple application for do that. Still need to move ```cleanModuleSymlinks/createModuleSymlinks ``` to another location.
You can look :)
[Haxey](https://github.com/halybang/haxey)

**Comment by npiganeau** [comment]
Ok. Can you make a PR ?

**Comment by npiganeau** [comment]
Done in 9f2d33fed3540b5b56507f26b7ca5547c9aacb5d
